list payments
kuutamolabs/lightning-knd pull request #404
Opened 2023-06-15 16:12 UTC by JosephGoulden

2023-06-16 05:20 UTC, yanganto requested changes

2023-06-16 05:20 UTC, yanganto commented on kld/src/database/payment.rs
> +            bolt11: Some(invoice.bolt11.to_string()),
The `lightning_invoice::Invoice` (bolt11 here) already includes a timestamp.  This will really confuse the user with a `SystemTime:now()`

2023-06-16 15:49 UTC, JosephGoulden commented on kld/src/database/payment.rs
> +    pub bolt11: Option<String>,
No. And there is no upper bound to the length. But maybe we will add a reasonable limit in the API request validation.

2023-06-17 09:59 UTC, merged

2023-06-19 01:22 UTC, yanganto commented on kld/src/database/payment.rs
> +            bolt11: Some(invoice.bolt11.to_string()),
Do you know if we will let the user query his payment in the future?

If it is, what is the user expect with a timestamp query?

If not why do we store `amount` and `timestamp` here?
We already hold `Invoice`, which includes `amount` and `timestamp`.

2023-06-19 01:29 UTC, yanganto commented on kld/src/database/payment.rs
> +    pub bolt11: Option<String>,
If there is a reasonable limit in the API layer, why we can not fix the size in DB?

2023-06-19 10:20 UTC, JosephGoulden commented on kld/src/database/payment.rs
> +    pub bolt11: Option<String>,
I don't know what the reasonable limit is at the moment. its good enough for now. yes maybe we can add a DB check in future.

2023-06-19 10:25 UTC, yanganto commented on kld/src/database/payment.rs
> +            bolt11: Some(invoice.bolt11.to_string()),
Okay, sorry about this, I am aware this timestamp is for a user, not the person who create the invoice.

2023-06-19 10:34 UTC, yanganto commented on kld/src/database/payment.rs
> +    pub bolt11: Option<String>,
The thing I did not say clearly is that I hope the field can be fixed-sized if it is possible and reasonable.  Such that the DB can have a better performance.  We can convert it to `[u8; n]` if we already have a limitation in the future.

2023-06-19 14:25 UTC, paulmattei commented on kld/src/database/payment.rs
> +    pub bolt11: Option<String>,
Tracking [here](https://github.com/kuutamolabs/lightning-knd/issues/411) to close off this thread