refactor test
kuutamolabs/lightning-knd pull request #605
Opened 2023-08-31 06:42 UTC by yanganto

fix #602, #604

2023-08-31 09:07 UTC, JosephGoulden requested changes
Good idea using tempdir!

2023-08-31 09:07 UTC, JosephGoulden commented on kld/tests/smoke/start.rs
> +    .await?;
The macros help by removing this boilerplate code but I can see how they are confusing. In the future we could have many more of these types of end to end test. We can find another way of hiding the setup code.

2023-08-31 09:07 UTC, JosephGoulden commented on kld/tests/api/rest.rs
> +    _tmp_dir: TempDir,
why the underscore?

2023-08-31 09:22 UTC, yanganto commented on test-utils/src/cockroach_manager.rs
> +        // Why we need an extra memory copy here?
It is a different thing. 
This is wrong typing in the `settings.database_port`, it should not be a string here.

2023-09-03 12:58 UTC, JosephGoulden reviewed
This still occasionally fails with 'bad file descriptor' on CI and on my desktop. 

Also I remembered that we use the target dir for test output so that it is easy to read the logs when the test fails. We can't do that with tempdir as it deletes them, so I don't think we can merge this.

2023-09-04 01:54 UTC, yanganto commented
> This still occasionally fails with 'bad file descriptor' on CI and on my desktop.

Even avoiding spawning multiple rm commands does not solve this issue, we should do it correctly.

> Also I remembered that we use the target dir for test output so that it is easy to read the logs when the test fails. We can't do that with tempdir as it deletes them, so I don't think we can merge this.

It is best practice to correct setup and tear down test cases.  If you want to keep the log from a test, you should use [keep](https://docs.rs/tempfile/3.8.0/tempfile/struct.NamedTempFile.html#method.keep), [persist](https://docs.rs/tempfile/3.8.0/tempfile/struct.NamedTempFile.html#method.persist) or [persist_noclobber](https://docs.rs/tempfile/3.8.0/tempfile/struct.NamedTempFile.html#method.persist_noclobber) to debug and develop the test case.  When running a regular test on a CI server or other developers' machine, these tests should not leave any file on the machine without any prompts.

2023-09-04 02:07 UTC, yanganto commented
FYI,

https://www.browserstack.com/guide/how-to-write-test-cases#toc5

> Create self-cleaning test cases. Test cases must revert the [Test Environment](https://www.browserstack.com/guide/what-is-test-environment) to a pristine, pre-test state. Tests should not leave remnants of themselves in the environment when completed. This is an integral element of Configuration Management. To understand more in-depth: [What is Configuration Management in DevOps?](https://www.browserstack.com/guide/configuration-management-in-devops)

2023-09-05 04:26 UTC, yanganto commented
Alright, you can set any path to store the artifacts from test cases like this command.

`KEEP_TEST_ARTIFACTS_IN=/tmp/kld-test cargo test test_start`

Just kindly note that the working folder is hidden (created by the library) under `KEEP_TEST_ARTIFACTS_IN`.

2023-09-06 08:44 UTC, yanganto commented
After today's meeting, the PR splits, and the keeping test artifacts will in #619

2023-09-06 08:44 UTC, merged